packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: ^5.2.2
  '@types/node': ^20.8.6
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^13.5.4
  firebase: ^10.5.0
  firebase-admin: ^11.11.0
  '@google-cloud/vertex-ai': ^1.4.0
  '@google-cloud/documentai': ^8.5.0
  '@google-cloud/translate': ^8.0.2
  '@google-cloud/text-to-speech': ^5.1.0
  tailwindcss: ^3.3.5
  framer-motion: ^10.16.4
  '@tanstack/react-query': ^4.36.1
  zustand: ^4.4.4
  react-hook-form: ^7.47.0
  zod: ^3.22.4
  recharts: ^2.8.0
  react-pdf: ^7.5.1
  '@radix-ui/react-accordion': ^1.1.2
  '@radix-ui/react-alert-dialog': ^1.0.5
  '@radix-ui/react-avatar': ^1.0.4
  '@radix-ui/react-button': ^0.1.0
  '@radix-ui/react-checkbox': ^1.0.4
  '@radix-ui/react-dialog': ^1.0.5
  '@radix-ui/react-dropdown-menu': ^2.0.6
  '@radix-ui/react-icons': ^1.3.0
  '@radix-ui/react-label': ^2.0.2
  '@radix-ui/react-popover': ^1.0.7
  '@radix-ui/react-progress': ^1.0.3
  '@radix-ui/react-radio-group': ^1.1.3
  '@radix-ui/react-select': ^2.0.0
  '@radix-ui/react-separator': ^1.0.3
  '@radix-ui/react-slider': ^1.1.2
  '@radix-ui/react-switch': ^1.0.3
  '@radix-ui/react-tabs': ^1.0.4
  '@radix-ui/react-toast': ^1.1.5
  '@radix-ui/react-toggle': ^1.0.3
  '@radix-ui/react-tooltip': ^1.0.7
  lucide-react: ^0.288.0
  class-variance-authority: ^0.7.0
  clsx: ^2.0.0
  tailwind-merge: ^1.14.0
  tailwindcss-animate: ^1.0.7